name: run action - this action is written in jobs

on: [push]

jobs:
    run-js:
      runs-on: ubuntu-latest
      steps:
        - name: List Files before checkout
          run: |
            pwd
            ls -a
        - name: checkout-actions list files after checkout
          uses: actions/checkout@v1
          run: |
            pwd
            ls -a
        - name: simple JS action
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: Ayan
        - name: time of exec of actions/hello-world-javascript-action
          run: echo "${{steps.greet.outputs.time}}"
