name: docker services

on: push

jobs:
  docker-container: # running docker container with using different images in ubuntu-vm
    runs-on: ubuntu-latest
    container:
      image: node:18-buster

    steps:
      - name : running command on 18-buster image-container
        run: node -v

      - name: running another image-container
        uses: docker://node:12.14.1-apline3.10
        with:
          entrypoint: "bin/bash"
          args: "hello world"

      - name: running another image-container
        uses: docker://node:12.14.1-apline3.10
        with:
          entrypoint: usr/local/bin/node
          args: -v
  docker-services: #running docker sevices
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000

      mongo:
        image: mongo
        ports:
          - "27017:27017"
  
    steps:
      - name: add user
        run: 'curl -X POST http://localhost:3001/api/user -H "Content-Type: application/json" -d "{\"username\": \"Hello\",\"address\": \"abcdef\"}"'

      - name: get users
        run: curl http://localhost:3001/api/users