name: shell comands

on: [push]

jobs:
    run-command: #first job
        runs-on: ubuntu-latest
        steps:
          - name: to run single run-command
            run: echo "hello world"
          - name: to run multiple commands
            run: |
                node -v
                npm -v
          - name: python commands
            run: |
                print('welcome')
                print(12*2)
            shell: python
    run-command-windows: #second job
        runs-on: windows-latest
        needs: ['run-command']
        steps:
          - name: powershell location
            run: Get-Location
          - name: directory bash
            run: pwd
            shell: bash
    
